// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Infrastructure.Data;

#nullable disable

namespace ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumOrderQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoastLevel")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("WeightInGrams")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-1111-4aaa-bbbb-000000000001"),
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Bright, floral, and fruity with a light body. Notes of jasmine, lemon, and blueberry.",
                            ImageUrl = "/assets/images/products/ethiopian-yirgacheffe.png",
                            IsActive = true,
                            IsFeatured = true,
                            MinimumOrderQuantity = 5,
                            Name = "Ethiopian Yirgacheffe",
                            Origin = "Ethiopia",
                            Price = 1850.00m,
                            RoastLevel = 1,
                            SKU = "ETH-YIR-01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeightInGrams = 1000.0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-2222-4aaa-bbbb-000000000002"),
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Well-balanced with mild acidity. Notes of caramel, chocolate, and walnut.",
                            ImageUrl = "/assets/images/products/colombian-supremo.png",
                            IsActive = true,
                            IsFeatured = true,
                            MinimumOrderQuantity = 5,
                            Name = "Colombian Supremo",
                            Origin = "Colombia",
                            Price = 1650.00m,
                            RoastLevel = 2,
                            SKU = "COL-SUP-01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeightInGrams = 1000.0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-3333-4aaa-bbbb-000000000003"),
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Authentic dark roast espresso blend with a thick crema and hints of spice and cocoa.",
                            ImageUrl = "/assets/images/products/italian-espresso.png",
                            IsActive = true,
                            IsFeatured = true,
                            MinimumOrderQuantity = 10,
                            Name = "Italian Espresso Classico",
                            Origin = "Italy/Brazil",
                            Price = 1550.00m,
                            RoastLevel = 4,
                            SKU = "ESP-ITA-01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeightInGrams = 1000.0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-5555-4aaa-bbbb-000000000005"),
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Famous for its complex flavor profile. Spicy, smokey, and chocolaty with floral hints.",
                            ImageUrl = "/assets/images/products/guatemala-antigua.png",
                            IsActive = true,
                            IsFeatured = false,
                            MinimumOrderQuantity = 5,
                            Name = "Guatemala Antigua",
                            Origin = "Guatemala",
                            Price = 1950.00m,
                            RoastLevel = 2,
                            SKU = "GUA-ANT-01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeightInGrams = 1000.0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-7777-4aaa-bbbb-000000000007"),
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Bright acidity and intense fruitiness. Notes of blackcurrant, wine, and citrus.",
                            ImageUrl = "/assets/images/products/kenya-aa.png",
                            IsActive = true,
                            IsFeatured = true,
                            MinimumOrderQuantity = 5,
                            Name = "Kenya AA Peaberry",
                            Origin = "Kenya",
                            Price = 2250.00m,
                            RoastLevel = 1,
                            SKU = "KEN-PEA-01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeightInGrams = 1000.0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-4444-4aaa-bbbb-000000000004"),
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Full-bodied Indonesian coffee with earthy, herbal complexity. Low acidity with a lingering dark chocolate and cedar finish.",
                            DiscountedPrice = 1880.00m,
                            ImageUrl = "/assets/images/products/sumatra-mandheling.png",
                            IsActive = true,
                            IsFeatured = false,
                            MinimumOrderQuantity = 5,
                            Name = "Sumatra Mandheling",
                            Origin = "Indonesia",
                            Price = 1920.00m,
                            RoastLevel = 4,
                            SKU = "SUM-MAN-01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeightInGrams = 1000.0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-6666-4aaa-bbbb-000000000006"),
                            Category = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Chemically-free Swiss Water Process decaf with all the flavor, none of the caffeine. Smooth, mellow, and perfect for evening cups.",
                            ImageUrl = "/assets/images/products/swiss-decaf.png",
                            IsActive = true,
                            IsFeatured = false,
                            MinimumOrderQuantity = 10,
                            Name = "Swiss Water Decaf Blend",
                            Origin = "Brazil/Peru",
                            Price = 1650.00m,
                            RoastLevel = 2,
                            SKU = "DEC-SWS-01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeightInGrams = 1000.0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-8888-4aaa-bbbb-000000000008"),
                            Category = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Pre-ground coarse blend optimized for 12-24hr cold extraction. Yields a smooth, low-acid concentrate with natural sweetness and chocolate notes.",
                            DiscountedPrice = 1499.00m,
                            ImageUrl = "/assets/images/products/cold-brew.png",
                            IsActive = true,
                            IsFeatured = false,
                            MinimumOrderQuantity = 10,
                            Name = "Cold Brew Concentrate",
                            Origin = "Brazil",
                            Price = 1550.00m,
                            RoastLevel = 3,
                            SKU = "CLD-BRW-01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeightInGrams = 1000.0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-9999-4aaa-bbbb-000000000009"),
                            Category = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "Bright and clean Costa Rican beans from the famed Tarrazu highlands. Honey-processed with notes of apricot, brown sugar, and a silky mouthfeel.",
                            ImageUrl = "/assets/images/products/costa-rica-tarrazu.png",
                            IsActive = true,
                            IsFeatured = false,
                            MinimumOrderQuantity = 5,
                            Name = "Costa Rica Tarrazu",
                            Origin = "Costa Rica",
                            Price = 1890.00m,
                            RoastLevel = 2,
                            SKU = "CRC-TAR-01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeightInGrams = 1000.0
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-aaaa-4aaa-bbbb-000000000010"),
                            Category = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "A luxurious house blend of Ethiopian and Brazilian beans with rich cocoa, toasted almond, and a whisper of vanilla. Perfect for lattes.",
                            DiscountedPrice = 1650.00m,
                            ImageUrl = "/assets/images/products/midnight-mocha.png",
                            IsActive = true,
                            IsFeatured = true,
                            MinimumOrderQuantity = 5,
                            Name = "Midnight Mocha Blend",
                            Origin = "Ethiopia/Brazil",
                            Price = 1690.00m,
                            RoastLevel = 3,
                            SKU = "BLD-MOC-01",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WeightInGrams = 1000.0
                        });
                });

            modelBuilder.Entity("ProductService.Domain.Entities.ProductReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("ProductService.Domain.Entities.ProductReview", b =>
                {
                    b.HasOne("ProductService.Domain.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductService.Domain.Entities.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
